#!/bin/bash

echo 0 >>/sys/devices/system/cpu/intel_pstate/no_turbo

Kp=100
Kdenom=2
DTnum=1000
DTdenom=1000
DTfloat=1 # this must equal Td/Tdenom
Ti=10
Td=5
Tddenom=10

tt="$(($1 * 1000))" # target temp in mC
echo "Target temp $tt"

e() {	# compute the error
	m=1000000000 # min undertemp
	for temp_i in /sys/devices/platform/coretemp.*/hwmon/hwmon*/temp*_input
	do
		t="$(cat $temp_i)" # temp
		d=$((tt - t)) # undertemp
		if ((d < m)) # min() algo
		then	m="${d}" # update min undertemp
			mi=$temp_i
			mt=$t
		fi
	done
	printf "%13s %2i/%2i" "$(cat "${mi%_input}_label")" "$((mt/1000))" "$((tt/1000))" >&2
	echo "$m" # min(undertemp)
}

maxc="$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)"
minc="$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq)"
changeSpeed() {
	u="$1"
	c="$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)"
	tc=$((c + u))
	if ((tc > maxc))
	then tc=$maxc
	fi
	if ((tc < minc))
	then tc=$minc
	fi
	for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq
	do	echo "$tc" >>$i
	done
	echo " set $tc $( cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq )" >&2
}

checkTrip() {
	c="$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)"
	if (( c < minc ))
	then echo "CPU TRIPPED ****************************************"
		for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq
		do	echo "$minc" >>$i
			prev_e=0
			int=0
		done
		sleep 1
	fi
}

prev_e=0
int=0

Tis=$(( Ti * DTdenom / DTnum ))
echo Integral time in samples: $Tis
Tds=$(( Td * DTdenom / DTnum ))
echo Differential time in samples: $Tds/$Tddenom

while true
do	et=$(e)
	p=$((et))
	d=$(( ( ( et - prev_e ) * DTdenom ) / DTnum )) # de/dt
	prev_e=$(( et ))
	d=$(( $d * Tds / $Tddenom )) # Td de/dt
#	echo $int $cmt $alpham
	int=$(( int + et ))
	i=$(( int * DTnum / DTdenom )) # int(0,t,e dt)
	i=$(( i / Tis )) # int(0,t,e dt) / Ti
	u=$(( $Kp * ( $p + $i + $d ) / $Kdenom ))
	printf ' %8i %8i %8i %8i' $p $i $d $u >&2
	changeSpeed $u
	sleep $DTfloat
	checkTrip
done
